### ISSUE TITLE
License

### ISSUE THREAD

**Issue by greimel** [mhaense1/SSJ_Julia_Notebook#1]
Hi @mhaense1,

thanks for sharing this great resource!

Please consider adding a license to this repository, so that people (like me) know under what conditions one can use this code.

I think some [creative commons](https://creativecommons.org/share-your-work/cclicenses/) would be a good choice for such a project. In that case you would permit using, adapting and redistributing your code (e.g. for teaching purposes) provided that you are given credit.

Thanks to you I am now considering covering Krusell-Smith in my course [greimel.github.io/distributional-macroeconomics/](https://greimel.github.io/distributional-macroeconomics/)

**Comment by mhaense1** [comment]
Thanks for your interest in my notebook and the suggestion. 

I now added a license to my file.
